# Generated by Django 5.1.2 on 2024-11-13 22:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nome', models.CharField(max_length=50)),
                ('usu_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_descricao', models.CharField(max_length=50)),
                ('tar_setor', models.CharField(max_length=50)),
                ('tar_prioridade', models.CharField(max_length=50)),
                ('tar_status', models.CharField(max_length=50)),
                ('tar_data', models.DateField(blank=True, null=True)),
                ('usu_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoDjango.usuario')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
